### ISSUE TITLE
Comments cannot infinite scroll

### ISSUE THREAD

**Issue by gerard-kanters** [gerard-kanters/infinite_scroll#1]
If the number of comments requires pagination (default 25 )this plugin messes up.  Probably cannot handle annotation.

**Comment by Wouter0100** [comment]
I'm unable to find the issue of this. [These](https://github.com/gerard-kanters/infinite_scroll/blob/master/views/default/infinite_scroll/list.php#L43-L45) lines of code doesn't work properly with the Visit Report plugin, as it seems like. I'm not sure what exactly causes this issue tho. Maybe the Visit Report plugin does something strange, or the Inifity Scroll plugin isn't working properly. [This](https://github.com/gerard-kanters/infinite_scroll/blob/master/views/default/infinite_scroll/list.php#L46-L50) function gives a strange response, which shouldn't be there. (The response which is being printed to the browser)

**Comment by Wouter0100** [comment]
Found and fixed in 99101ed29e65c880e729cd950c441ab0ff19391b. Plugin is updated on prod.
